package db;
// Generated Jun 26, 2017 5:09:54 PM by Hibernate Tools 4.3.1



/**
 * Agenda generated by hbm2java
 */
public class Agenda  implements java.io.Serializable {


     private Integer idAgenda;
     private Program program;
     private Subsctiption subsctiption;

    public Agenda() {
    }

    public Agenda(Program program, Subsctiption subsctiption) {
       this.program = program;
       this.subsctiption = subsctiption;
    }
   
    public Integer getIdAgenda() {
        return this.idAgenda;
    }
    
    public void setIdAgenda(Integer idAgenda) {
        this.idAgenda = idAgenda;
    }
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }
    public Subsctiption getSubsctiption() {
        return this.subsctiption;
    }
    
    public void setSubsctiption(Subsctiption subsctiption) {
        this.subsctiption = subsctiption;
    }




}


