package db;
// Generated Jun 26, 2017 5:09:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conference generated by hbm2java
 */
public class Conference  implements java.io.Serializable {


     private Integer idConference;
     private Field field;
     private String name;
     private Date startDate;
     private Date endDate;
     private String password;
     private String location;
     private boolean calledOff;
     private Set programs = new HashSet(0);
     private Set moderators = new HashSet(0);
     private Set subsctiptions = new HashSet(0);

    public Conference() {
    }

	
    public Conference(Field field, String name, Date startDate, Date endDate, String password, boolean calledOff) {
        this.field = field;
        this.name = name;
        this.startDate = startDate;
        this.endDate = endDate;
        this.password = password;
        this.calledOff = calledOff;
    }
    public Conference(Field field, String name, Date startDate, Date endDate, String password, String location, boolean calledOff, Set programs, Set moderators, Set subsctiptions) {
       this.field = field;
       this.name = name;
       this.startDate = startDate;
       this.endDate = endDate;
       this.password = password;
       this.location = location;
       this.calledOff = calledOff;
       this.programs = programs;
       this.moderators = moderators;
       this.subsctiptions = subsctiptions;
    }
   
    public Integer getIdConference() {
        return this.idConference;
    }
    
    public void setIdConference(Integer idConference) {
        this.idConference = idConference;
    }
    public Field getField() {
        return this.field;
    }
    
    public void setField(Field field) {
        this.field = field;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }
    public boolean isCalledOff() {
        return this.calledOff;
    }
    
    public void setCalledOff(boolean calledOff) {
        this.calledOff = calledOff;
    }
    public Set getPrograms() {
        return this.programs;
    }
    
    public void setPrograms(Set programs) {
        this.programs = programs;
    }
    public Set getModerators() {
        return this.moderators;
    }
    
    public void setModerators(Set moderators) {
        this.moderators = moderators;
    }
    public Set getSubsctiptions() {
        return this.subsctiptions;
    }
    
    public void setSubsctiptions(Set subsctiptions) {
        this.subsctiptions = subsctiptions;
    }




}


