package db;
// Generated Jun 26, 2017 5:09:54 PM by Hibernate Tools 4.3.1



/**
 * FavouriteId generated by hbm2java
 */
public class FavouriteId  implements java.io.Serializable {


     private int userIdUserSrc;
     private int userIdUserDst;

    public FavouriteId() {
    }

    public FavouriteId(int userIdUserSrc, int userIdUserDst) {
       this.userIdUserSrc = userIdUserSrc;
       this.userIdUserDst = userIdUserDst;
    }
   
    public int getUserIdUserSrc() {
        return this.userIdUserSrc;
    }
    
    public void setUserIdUserSrc(int userIdUserSrc) {
        this.userIdUserSrc = userIdUserSrc;
    }
    public int getUserIdUserDst() {
        return this.userIdUserDst;
    }
    
    public void setUserIdUserDst(int userIdUserDst) {
        this.userIdUserDst = userIdUserDst;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FavouriteId) ) return false;
		 FavouriteId castOther = ( FavouriteId ) other; 
         
		 return (this.getUserIdUserSrc()==castOther.getUserIdUserSrc())
 && (this.getUserIdUserDst()==castOther.getUserIdUserDst());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserIdUserSrc();
         result = 37 * result + this.getUserIdUserDst();
         return result;
   }   


}


