package db;
// Generated Jun 26, 2017 5:09:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Field generated by hbm2java
 */
public class Field  implements java.io.Serializable {


     private Integer idField;
     private String field;
     private Set conferences = new HashSet(0);

    public Field() {
    }

    public Field(String field, Set conferences) {
       this.field = field;
       this.conferences = conferences;
    }
   
    public Integer getIdField() {
        return this.idField;
    }
    
    public void setIdField(Integer idField) {
        this.idField = idField;
    }
    public String getField() {
        return this.field;
    }
    
    public void setField(String field) {
        this.field = field;
    }
    public Set getConferences() {
        return this.conferences;
    }
    
    public void setConferences(Set conferences) {
        this.conferences = conferences;
    }




}


