package db;
// Generated Jun 26, 2017 5:09:54 PM by Hibernate Tools 4.3.1



/**
 * File generated by hbm2java
 */
public class File  implements java.io.Serializable {


     private Integer idFile;
     private Talk talk;
     private String link;

    public File() {
    }

    public File(Talk talk, String link) {
       this.talk = talk;
       this.link = link;
    }
   
    public Integer getIdFile() {
        return this.idFile;
    }
    
    public void setIdFile(Integer idFile) {
        this.idFile = idFile;
    }
    public Talk getTalk() {
        return this.talk;
    }
    
    public void setTalk(Talk talk) {
        this.talk = talk;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }




}


