package db;
// Generated Jun 26, 2017 5:09:54 PM by Hibernate Tools 4.3.1



/**
 * ModeratorId generated by hbm2java
 */
public class ModeratorId  implements java.io.Serializable {


     private int userIdUser;
     private int conferenceIdConference;

    public ModeratorId() {
    }

    public ModeratorId(int userIdUser, int conferenceIdConference) {
       this.userIdUser = userIdUser;
       this.conferenceIdConference = conferenceIdConference;
    }
   
    public int getUserIdUser() {
        return this.userIdUser;
    }
    
    public void setUserIdUser(int userIdUser) {
        this.userIdUser = userIdUser;
    }
    public int getConferenceIdConference() {
        return this.conferenceIdConference;
    }
    
    public void setConferenceIdConference(int conferenceIdConference) {
        this.conferenceIdConference = conferenceIdConference;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ModeratorId) ) return false;
		 ModeratorId castOther = ( ModeratorId ) other; 
         
		 return (this.getUserIdUser()==castOther.getUserIdUser())
 && (this.getConferenceIdConference()==castOther.getConferenceIdConference());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserIdUser();
         result = 37 * result + this.getConferenceIdConference();
         return result;
   }   


}


