package db;
// Generated Jun 26, 2017 5:09:54 PM by Hibernate Tools 4.3.1



/**
 * Moderator generated by hbm2java
 */
public class Moderator  implements java.io.Serializable {


     private ModeratorId id;
     private Conference conference;
     private User user;
     private Integer pad;

    public Moderator() {
    }

	
    public Moderator(ModeratorId id, Conference conference, User user) {
        this.id = id;
        this.conference = conference;
        this.user = user;
    }
    public Moderator(ModeratorId id, Conference conference, User user, Integer pad) {
       this.id = id;
       this.conference = conference;
       this.user = user;
       this.pad = pad;
    }
   
    public ModeratorId getId() {
        return this.id;
    }
    
    public void setId(ModeratorId id) {
        this.id = id;
    }
    public Conference getConference() {
        return this.conference;
    }
    
    public void setConference(Conference conference) {
        this.conference = conference;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Integer getPad() {
        return this.pad;
    }
    
    public void setPad(Integer pad) {
        this.pad = pad;
    }




}


