package db;
// Generated Jun 26, 2017 5:09:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Openingorclosingtalk generated by hbm2java
 */
public class Openingorclosingtalk  implements java.io.Serializable {


     private Integer idOpeningOrClosingTalk;
     private Ceremony ceremony;
     private Session session;
     private Date startTime;
     private Date endTime;
     private Set authors = new HashSet(0);

    public Openingorclosingtalk() {
    }

	
    public Openingorclosingtalk(Date startTime, Date endTime) {
        this.startTime = startTime;
        this.endTime = endTime;
    }
    public Openingorclosingtalk(Ceremony ceremony, Session session, Date startTime, Date endTime, Set authors) {
       this.ceremony = ceremony;
       this.session = session;
       this.startTime = startTime;
       this.endTime = endTime;
       this.authors = authors;
    }
   
    public Integer getIdOpeningOrClosingTalk() {
        return this.idOpeningOrClosingTalk;
    }
    
    public void setIdOpeningOrClosingTalk(Integer idOpeningOrClosingTalk) {
        this.idOpeningOrClosingTalk = idOpeningOrClosingTalk;
    }
    public Ceremony getCeremony() {
        return this.ceremony;
    }
    
    public void setCeremony(Ceremony ceremony) {
        this.ceremony = ceremony;
    }
    public Session getSession() {
        return this.session;
    }
    
    public void setSession(Session session) {
        this.session = session;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public Set getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(Set authors) {
        this.authors = authors;
    }




}


