package db;
// Generated Jun 26, 2017 5:09:54 PM by Hibernate Tools 4.3.1



/**
 * Photo generated by hbm2java
 */
public class Photo  implements java.io.Serializable {


     private Integer idPhoto;
     private Program program;
     private String link;

    public Photo() {
    }

    public Photo(Program program, String link) {
       this.program = program;
       this.link = link;
    }
   
    public Integer getIdPhoto() {
        return this.idPhoto;
    }
    
    public void setIdPhoto(Integer idPhoto) {
        this.idPhoto = idPhoto;
    }
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }
    public String getLink() {
        return this.link;
    }
    
    public void setLink(String link) {
        this.link = link;
    }




}


