package db;
// Generated Jun 26, 2017 5:09:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Program generated by hbm2java
 */
public class Program  implements java.io.Serializable {


     private Integer idProgram;
     private Conference conference;
     private Date startDateTime;
     private Date endDateTime;
     private String hall;
     private Set agendas = new HashSet(0);
     private Set comments = new HashSet(0);
     private Set photos = new HashSet(0);
     private Workshop workshop;
     private Session session;
     private Ceremony ceremony;

    public Program() {
    }

	
    public Program(Conference conference, Date startDateTime, Date endDateTime, String hall) {
        this.conference = conference;
        this.startDateTime = startDateTime;
        this.endDateTime = endDateTime;
        this.hall = hall;
    }
    public Program(Conference conference, Date startDateTime, Date endDateTime, String hall, Set agendas, Set comments, Set photos, Workshop workshop, Session session, Ceremony ceremony) {
       this.conference = conference;
       this.startDateTime = startDateTime;
       this.endDateTime = endDateTime;
       this.hall = hall;
       this.agendas = agendas;
       this.comments = comments;
       this.photos = photos;
       this.workshop = workshop;
       this.session = session;
       this.ceremony = ceremony;
    }
   
    public Integer getIdProgram() {
        return this.idProgram;
    }
    
    public void setIdProgram(Integer idProgram) {
        this.idProgram = idProgram;
    }
    public Conference getConference() {
        return this.conference;
    }
    
    public void setConference(Conference conference) {
        this.conference = conference;
    }
    public Date getStartDateTime() {
        return this.startDateTime;
    }
    
    public void setStartDateTime(Date startDateTime) {
        this.startDateTime = startDateTime;
    }
    public Date getEndDateTime() {
        return this.endDateTime;
    }
    
    public void setEndDateTime(Date endDateTime) {
        this.endDateTime = endDateTime;
    }
    public String getHall() {
        return this.hall;
    }
    
    public void setHall(String hall) {
        this.hall = hall;
    }
    public Set getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set agendas) {
        this.agendas = agendas;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }
    public Set getPhotos() {
        return this.photos;
    }
    
    public void setPhotos(Set photos) {
        this.photos = photos;
    }
    public Workshop getWorkshop() {
        return this.workshop;
    }
    
    public void setWorkshop(Workshop workshop) {
        this.workshop = workshop;
    }
    public Session getSession() {
        return this.session;
    }
    
    public void setSession(Session session) {
        this.session = session;
    }
    public Ceremony getCeremony() {
        return this.ceremony;
    }
    
    public void setCeremony(Ceremony ceremony) {
        this.ceremony = ceremony;
    }




}


