package db;
// Generated Jun 26, 2017 5:09:54 PM by Hibernate Tools 4.3.1



/**
 * RatingId generated by hbm2java
 */
public class RatingId  implements java.io.Serializable {


     private int userIdUser;
     private int talkIdTalk;

    public RatingId() {
    }

    public RatingId(int userIdUser, int talkIdTalk) {
       this.userIdUser = userIdUser;
       this.talkIdTalk = talkIdTalk;
    }
   
    public int getUserIdUser() {
        return this.userIdUser;
    }
    
    public void setUserIdUser(int userIdUser) {
        this.userIdUser = userIdUser;
    }
    public int getTalkIdTalk() {
        return this.talkIdTalk;
    }
    
    public void setTalkIdTalk(int talkIdTalk) {
        this.talkIdTalk = talkIdTalk;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RatingId) ) return false;
		 RatingId castOther = ( RatingId ) other; 
         
		 return (this.getUserIdUser()==castOther.getUserIdUser())
 && (this.getTalkIdTalk()==castOther.getTalkIdTalk());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getUserIdUser();
         result = 37 * result + this.getTalkIdTalk();
         return result;
   }   


}


