package db;
// Generated Jun 26, 2017 5:09:54 PM by Hibernate Tools 4.3.1



/**
 * Rating generated by hbm2java
 */
public class Rating  implements java.io.Serializable {


     private RatingId id;
     private Talk talk;
     private User user;
     private int rating;

    public Rating() {
    }

    public Rating(RatingId id, Talk talk, User user, int rating) {
       this.id = id;
       this.talk = talk;
       this.user = user;
       this.rating = rating;
    }
   
    public RatingId getId() {
        return this.id;
    }
    
    public void setId(RatingId id) {
        this.id = id;
    }
    public Talk getTalk() {
        return this.talk;
    }
    
    public void setTalk(Talk talk) {
        this.talk = talk;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getRating() {
        return this.rating;
    }
    
    public void setRating(int rating) {
        this.rating = rating;
    }




}


