package db;
// Generated Jun 26, 2017 5:09:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Session generated by hbm2java
 */
public class Session  implements java.io.Serializable {


     private int programIdProgram;
     private Program program;
     private String title;
     private Set talks = new HashSet(0);
     private Set openingorclosingtalks = new HashSet(0);

    public Session() {
    }

	
    public Session(Program program, String title) {
        this.program = program;
        this.title = title;
    }
    public Session(Program program, String title, Set talks, Set openingorclosingtalks) {
       this.program = program;
       this.title = title;
       this.talks = talks;
       this.openingorclosingtalks = openingorclosingtalks;
    }
   
    public int getProgramIdProgram() {
        return this.programIdProgram;
    }
    
    public void setProgramIdProgram(int programIdProgram) {
        this.programIdProgram = programIdProgram;
    }
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Set getTalks() {
        return this.talks;
    }
    
    public void setTalks(Set talks) {
        this.talks = talks;
    }
    public Set getOpeningorclosingtalks() {
        return this.openingorclosingtalks;
    }
    
    public void setOpeningorclosingtalks(Set openingorclosingtalks) {
        this.openingorclosingtalks = openingorclosingtalks;
    }




}


