package db;
// Generated Jun 26, 2017 5:09:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subsctiption generated by hbm2java
 */
public class Subsctiption  implements java.io.Serializable {


     private Integer idSubscription;
     private Conference conference;
     private User user;
     private Set agendas = new HashSet(0);

    public Subsctiption() {
    }

	
    public Subsctiption(Conference conference, User user) {
        this.conference = conference;
        this.user = user;
    }
    public Subsctiption(Conference conference, User user, Set agendas) {
       this.conference = conference;
       this.user = user;
       this.agendas = agendas;
    }
   
    public Integer getIdSubscription() {
        return this.idSubscription;
    }
    
    public void setIdSubscription(Integer idSubscription) {
        this.idSubscription = idSubscription;
    }
    public Conference getConference() {
        return this.conference;
    }
    
    public void setConference(Conference conference) {
        this.conference = conference;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Set getAgendas() {
        return this.agendas;
    }
    
    public void setAgendas(Set agendas) {
        this.agendas = agendas;
    }




}


