package db;
// Generated Jun 26, 2017 5:09:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Talk generated by hbm2java
 */
public class Talk  implements java.io.Serializable {


     private Integer idTalk;
     private Session session;
     private String title;
     private Date startTime;
     private Date endTime;
     private int sessionIdSession;
     private Set authors = new HashSet(0);
     private Set files = new HashSet(0);
     private Set ratings = new HashSet(0);

    public Talk() {
    }

	
    public Talk(Session session, String title, Date startTime, Date endTime, int sessionIdSession) {
        this.session = session;
        this.title = title;
        this.startTime = startTime;
        this.endTime = endTime;
        this.sessionIdSession = sessionIdSession;
    }
    public Talk(Session session, String title, Date startTime, Date endTime, int sessionIdSession, Set authors, Set files, Set ratings) {
       this.session = session;
       this.title = title;
       this.startTime = startTime;
       this.endTime = endTime;
       this.sessionIdSession = sessionIdSession;
       this.authors = authors;
       this.files = files;
       this.ratings = ratings;
    }
   
    public Integer getIdTalk() {
        return this.idTalk;
    }
    
    public void setIdTalk(Integer idTalk) {
        this.idTalk = idTalk;
    }
    public Session getSession() {
        return this.session;
    }
    
    public void setSession(Session session) {
        this.session = session;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public int getSessionIdSession() {
        return this.sessionIdSession;
    }
    
    public void setSessionIdSession(int sessionIdSession) {
        this.sessionIdSession = sessionIdSession;
    }
    public Set getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(Set authors) {
        this.authors = authors;
    }
    public Set getFiles() {
        return this.files;
    }
    
    public void setFiles(Set files) {
        this.files = files;
    }
    public Set getRatings() {
        return this.ratings;
    }
    
    public void setRatings(Set ratings) {
        this.ratings = ratings;
    }




}


