package db;
// Generated Jun 26, 2017 5:09:54 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer idUser;
     private String name;
     private String surname;
     private String email;
     private String institution;
     private String username;
     private String password;
     private char gender;
     private String size;
     private String linkedIn;
     private boolean isAdmin;
     private Set comments = new HashSet(0);
     private Set messages = new HashSet(0);
     private Set moderators = new HashSet(0);
     private Set ratings = new HashSet(0);
     private Set favouritesForUserIdUserSrc = new HashSet(0);
     private Set favouritesForUserIdUserDst = new HashSet(0);
     private Set authors = new HashSet(0);
     private Set subsctiptions = new HashSet(0);

    public User() {
    }

	
    public User(String name, String surname, String email, String institution, String username, String password, char gender, String size, boolean isAdmin) {
        this.name = name;
        this.surname = surname;
        this.email = email;
        this.institution = institution;
        this.username = username;
        this.password = password;
        this.gender = gender;
        this.size = size;
        this.isAdmin = isAdmin;
    }
    public User(String name, String surname, String email, String institution, String username, String password, char gender, String size, String linkedIn, boolean isAdmin, Set comments, Set messages, Set moderators, Set ratings, Set favouritesForUserIdUserSrc, Set favouritesForUserIdUserDst, Set authors, Set subsctiptions) {
       this.name = name;
       this.surname = surname;
       this.email = email;
       this.institution = institution;
       this.username = username;
       this.password = password;
       this.gender = gender;
       this.size = size;
       this.linkedIn = linkedIn;
       this.isAdmin = isAdmin;
       this.comments = comments;
       this.messages = messages;
       this.moderators = moderators;
       this.ratings = ratings;
       this.favouritesForUserIdUserSrc = favouritesForUserIdUserSrc;
       this.favouritesForUserIdUserDst = favouritesForUserIdUserDst;
       this.authors = authors;
       this.subsctiptions = subsctiptions;
    }
   
    public Integer getIdUser() {
        return this.idUser;
    }
    
    public void setIdUser(Integer idUser) {
        this.idUser = idUser;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getInstitution() {
        return this.institution;
    }
    
    public void setInstitution(String institution) {
        this.institution = institution;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public char getGender() {
        return this.gender;
    }
    
    public void setGender(char gender) {
        this.gender = gender;
    }
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }
    public String getLinkedIn() {
        return this.linkedIn;
    }
    
    public void setLinkedIn(String linkedIn) {
        this.linkedIn = linkedIn;
    }
    public boolean isIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public Set getComments() {
        return this.comments;
    }
    
    public void setComments(Set comments) {
        this.comments = comments;
    }
    public Set getMessages() {
        return this.messages;
    }
    
    public void setMessages(Set messages) {
        this.messages = messages;
    }
    public Set getModerators() {
        return this.moderators;
    }
    
    public void setModerators(Set moderators) {
        this.moderators = moderators;
    }
    public Set getRatings() {
        return this.ratings;
    }
    
    public void setRatings(Set ratings) {
        this.ratings = ratings;
    }
    public Set getFavouritesForUserIdUserSrc() {
        return this.favouritesForUserIdUserSrc;
    }
    
    public void setFavouritesForUserIdUserSrc(Set favouritesForUserIdUserSrc) {
        this.favouritesForUserIdUserSrc = favouritesForUserIdUserSrc;
    }
    public Set getFavouritesForUserIdUserDst() {
        return this.favouritesForUserIdUserDst;
    }
    
    public void setFavouritesForUserIdUserDst(Set favouritesForUserIdUserDst) {
        this.favouritesForUserIdUserDst = favouritesForUserIdUserDst;
    }
    public Set getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(Set authors) {
        this.authors = authors;
    }
    public Set getSubsctiptions() {
        return this.subsctiptions;
    }
    
    public void setSubsctiptions(Set subsctiptions) {
        this.subsctiptions = subsctiptions;
    }




}


