package db;
// Generated Jun 26, 2017 5:09:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Welcomingspeech generated by hbm2java
 */
public class Welcomingspeech  implements java.io.Serializable {


     private Integer idWelcomingSpeech;
     private Ceremony ceremony;
     private Date startTime;
     private Date endTime;
     private int ceremonyIdCeremony;
     private Set authors = new HashSet(0);

    public Welcomingspeech() {
    }

	
    public Welcomingspeech(Ceremony ceremony, Date startTime, Date endTime, int ceremonyIdCeremony) {
        this.ceremony = ceremony;
        this.startTime = startTime;
        this.endTime = endTime;
        this.ceremonyIdCeremony = ceremonyIdCeremony;
    }
    public Welcomingspeech(Ceremony ceremony, Date startTime, Date endTime, int ceremonyIdCeremony, Set authors) {
       this.ceremony = ceremony;
       this.startTime = startTime;
       this.endTime = endTime;
       this.ceremonyIdCeremony = ceremonyIdCeremony;
       this.authors = authors;
    }
   
    public Integer getIdWelcomingSpeech() {
        return this.idWelcomingSpeech;
    }
    
    public void setIdWelcomingSpeech(Integer idWelcomingSpeech) {
        this.idWelcomingSpeech = idWelcomingSpeech;
    }
    public Ceremony getCeremony() {
        return this.ceremony;
    }
    
    public void setCeremony(Ceremony ceremony) {
        this.ceremony = ceremony;
    }
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }
    public int getCeremonyIdCeremony() {
        return this.ceremonyIdCeremony;
    }
    
    public void setCeremonyIdCeremony(int ceremonyIdCeremony) {
        this.ceremonyIdCeremony = ceremonyIdCeremony;
    }
    public Set getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(Set authors) {
        this.authors = authors;
    }




}


