package db;
// Generated Jun 26, 2017 5:09:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Workshop generated by hbm2java
 */
public class Workshop  implements java.io.Serializable {


     private int programIdProgram;
     private Program program;
     private String title;
     private Date startDateTime;
     private Date endDateTime;
     private Set authors = new HashSet(0);

    public Workshop() {
    }

	
    public Workshop(Program program, String title, Date startDateTime, Date endDateTime) {
        this.program = program;
        this.title = title;
        this.startDateTime = startDateTime;
        this.endDateTime = endDateTime;
    }
    public Workshop(Program program, String title, Date startDateTime, Date endDateTime, Set authors) {
       this.program = program;
       this.title = title;
       this.startDateTime = startDateTime;
       this.endDateTime = endDateTime;
       this.authors = authors;
    }
   
    public int getProgramIdProgram() {
        return this.programIdProgram;
    }
    
    public void setProgramIdProgram(int programIdProgram) {
        this.programIdProgram = programIdProgram;
    }
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getStartDateTime() {
        return this.startDateTime;
    }
    
    public void setStartDateTime(Date startDateTime) {
        this.startDateTime = startDateTime;
    }
    public Date getEndDateTime() {
        return this.endDateTime;
    }
    
    public void setEndDateTime(Date endDateTime) {
        this.endDateTime = endDateTime;
    }
    public Set getAuthors() {
        return this.authors;
    }
    
    public void setAuthors(Set authors) {
        this.authors = authors;
    }




}


